### ISSUE TITLE
Allow using non-temp data dir

### ISSUE THREAD

**Issue by rajarshimaitra** [RCasatta/electrsd#35]
To create automated regtest backend for bdk-cli (https://github.com/bitcoindevkit/bdk-cli/issues/76) we need to have the option to create a non-temp data dir, inside the bdk wallet directory, so the node states can be made persistent between runs..

This issue is opened to get generic approach on doing that.. I am thinking of making the `Electrsd` `data_dir` optional, which defaults to temp directory if provide with `None`.

Happy to open a PR on both eletrsd and bitcoind if this sounds reasonable..

**Comment by RCasatta** [comment]
It sounds reasonable, in bitcoind should be already supported

https://github.com/RCasatta/bitcoind/commit/b91644170348290c28f1fcc90ffc8370e69bee65

**Comment by rajarshimaitra** [comment]
From the code it seems like bitcoind is still creating a `TempDir` if a path is given.. 
https://github.com/RCasatta/bitcoind/blob/493c0f4153e43fb4a0a10778ee1c90df1883aa2b/src/lib.rs#L174-L179

What we need is a persistent DB that is not Temp.. So maybe create normal directory with an option flag? I am thinking another option in in `Conf` struct like "persistent db" to signal weather datadir should be temp or persistent?

**Comment by rajarshimaitra** [comment]
Turns out its not that simple because of the way `TempDir` is dropped after end scope.. I ended up creating another enum `DataDir` for `BitcoinD`, like `P2P`, to hold the `TempDir` optionally.

Let me know if that approach makes sense..

https://github.com/RCasatta/bitcoind/pull/52/files

**Comment by RCasatta** [comment]
Ah yeah sorry it is not the same... Going to have a look at RCasatta/bitcoind#52
